### ISSUE TITLE
Unexpected Behaviour During Custom Build

### ISSUE THREAD

**Issue by schkovich** [arobenko/cc.mqtt5.libs#4]
Hello!

I encountered an issue building the library, having `CC_MQTT5_CLIENT_DEFAULT_LIB` set to `OFF` and `CC_MQTT5_CUSTOM_CLIENT_CONFIG_FILES` holding the correct path to the custom configuration file.  

### Current Behavior:
The build stops with the following output:
```bash
home/ubuntu/cc.mqtt5.libs/CMakeLists.txt(66):  add_subdirectory(client )
/home/ubuntu/cc.mqtt5.libs/client/CMakeLists.txt(1):  add_subdirectory(lib )
/home/ubuntu/cc.mqtt5.libs/client/lib/CMakeLists.txt(1):  if(( NOT CC_MQTT5_CLIENT_DEFAULT_LIB ) OR ( CC_MQTT5_CUSTOM_CLIENT_CONFIG_FILES STREQUAL  ) )
/home/ubuntu/cc.mqtt5.libs/client/lib/CMakeLists.txt(2):  return()
/home/ubuntu/cc.mqtt5.libs/client/CMakeLists.txt(2):  add_subdirectory(app )
/home/ubuntu/cc.mqtt5.libs/client/app/CMakeLists.txt(1):  if(NOT CC_MQTT5_CLIENT_APPS )
/home/ubuntu/cc.mqtt5.libs/client/app/CMakeLists.txt(2):  return()
/home/ubuntu/cc.mqtt5.libs/client/CMakeLists.txt(3):  add_subdirectory(afl_fuzz )
/home/ubuntu/cc.mqtt5.libs/client/afl_fuzz/CMakeLists.txt(1):  if(NOT CC_MQTT5_CLIENT_AFL_FUZZ )
/home/ubuntu/cc.mqtt5.libs/client/afl_fuzz/CMakeLists.txt(2):  return()
-- Configuring done (0.7s)
-- Generating done (0.0s)
-- Build files have been written to: /home/ubuntu/cc.mqtt5.libs/bm-build
Change Dir: '/home/ubuntu/cc.mqtt5.libs/bm-build'

Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile -j8 install
gmake: Nothing to be done for 'install'.
```
### Findings:
The if statement at the top of [client/lib/CMakeLists.txt](https://github.com/commschamp/cc.mqtt5.libs/blob/6990c0890748b55d67705323c44ad51f3cab2ea9/client/lib/CMakeLists.txt#L1) evaluates to true and returns.

* When `CC_MQTT5_CLIENT_DEFAULT_LIB` is set to `OFF`, the expression `(NOT CC_MQTT5_CLIENT_DEFAULT_LIB)` evaluates to `TRUE`. Since the condition uses `OR`, the right-hand side `(CC_MQTT5_CUSTOM_CLIENT_CONFIG_FILES STREQUAL "")` is not considered due to short-circuiting.

* This causes the build to stop even if a valid `CC_MQTT5_CUSTOM_CLIENT_CONFIG_FILES` value is provided.

### Host Environment:
**OS:** Ubuntu 24.04 Server
**CMake:** Version 3.28.3
**ARM Toolchain:** arm-none-eabi-gcc (Version 13.2.1)

The behaviour was observed in the same environment and conditions as #3.

### Steps to Reproduce:
* Use the following minimal CMakeLists.txt file:
```cmake
cmake_minimum_required(VERSION 3.14)

project(TestSTREQUAL)

# Simulate the input passed from the command line
set(CC_MQTT5_CLIENT_DEFAULT_LIB OFF)
set(CC_MQTT5_CUSTOM_CLIENT_CONFIG_FILES "/path/to/config.cmake")

if ((NOT CC_MQTT5_CLIENT_DEFAULT_LIB) OR
    (CC_MQTT5_CUSTOM_CLIENT_CONFIG_FILES STREQUAL ""))
    message(WARNING "Condition triggered!")
endif ()
```
* Run the following command:
```bash
cmake -S . -B build
```
* Observe the output:
```bash
Re-run cmake no build system arguments
CMake Warning at CMakeLists.txt:11 (message):
  Condition triggered!


-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /home/ubuntu/testme/build
```
### Expected Behavior:
* If `CC_MQTT5_CLIENT_DEFAULT_LIB=OFF` is intended to mean "_disable the default library but expect custom configurations,_" the condition should instead require both conditions to be true:
```cmake
if ((NOT CC_MQTT5_CLIENT_DEFAULT_LIB) AND
    (CC_MQTT5_CUSTOM_CLIENT_CONFIG_FILES STREQUAL ""))
    return()
endif ()
```
* This ensures that the build only stops if:
  * The default library is disabled.
  * No custom configuration is provided.
### Questions:
* Could you confirm the intended behaviour of CC_MQTT5_CLIENT_DEFAULT_LIB=OFF?
* If the current behaviour is intentional, could the documentation clarify the implications of this setting?

Let me know if further details are needed. Thank you for your time!

**Comment by arobenko** [comment]
Yes, you're right the condition should be `AND` instead of `OR`.
Fixed currently on the "develop" branch.
Please develop with "develop" branch for now. Once you consider all your issues resolved please let me know, I'll do an official "patch" release.

**Comment by schkovich** [comment]
I have already tested it in a local branch and the change works as expected. I would submit a PR but I was not sure of your intentions. 

GitHub might have a cache issue, or you forgot to push changes. :smile:

**Comment by arobenko** [comment]
As I mentioned in #3, I did introduce fixes to the wrong project.

**Comment by arobenko** [comment]
Fix merged to master, use [v1.0.2](https://github.com/commschamp/cc.mqtt5.libs/releases/tag/v1.0.2) release from now on.
